### ISSUE TITLE
Twitch Parser

### ISSUE THREAD

**Issue by pedrolucasmag** [wololodev/d2mt#26]
Twitch parser not working , need to get client_id:

https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.diljs51xd

**Comment by wololodev** [comment]
i know this is bad practice but I cant do much.. can you gen one and commit the php code necessary? I have auto-pull turned on so it'll reflect on the extension instantly.. @pedrolucasmag
